#!/usr/bin/env python

from database import *
from sys import argv, exit

if len(argv) == 1:
    print("Usage: \ntask start\ntask finish")
    exit(1)

create_database_if_not_present()

if argv[0] == "start":
    print("task 2 started")
elif argv[1] == "finish":
    print("task 2 finished")
